version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: filmderBdd
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234567aA*"  
      MYSQL_DATABASE: "FilmDerDataBase"       
    ports:
      - "3336:3306"
    volumes:
      - ./bdd/bdd.sql:/docker-entrypoint-initdb.d/bdd.sql
      - mysql_data:/var/lib/mysql


  mongo:
    image: mongo:6.0
    container_name: fastapi_logs
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: fastapi_logs


volumes:
  mysql_data:
  mongo_data:

