version: '3.8'

services:
  back:
    build:
      context: ./back 
      dockerfile: Dockerfile   
    container_name: back
    env_file:
      - .env
    depends_on:
      - mysql
      - mongo
    ports:
      - '8000:8000'  

  frontend:
      build:
        context: ./frontend 
        dockerfile: Dockerfile   
      container_name: frontend
      env_file:
        - .env
      ports:
      - '8080:80'  
  
  
  mysql:
    image: mysql:8.0
    container_name: filmderBdd
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_NAME}      
    ports:
      - "3336:3306"
    volumes:
      - ./bdd/bdd.sql:/docker-entrypoint-initdb.d/bdd.sql
      - mysql_data:/var/lib/mysql


  mongo:
    image: mongo:6.0
    container_name: filmderMongo
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}

volumes:
  mysql_data:
  mongo_data: